pub const MERGED_FILE_NAME: &str = "merged_isoform.dat";
pub const CHROM_FILE_NAME: &str = "chrom.map";
pub const TMPIDX_FILE_NAME: &str = "tmp.idx";
pub const DATASET_INFO_FILE_NAME: &str = "merged_isoform.info";
pub const META_FILE_NAME: &str = "meta.txt";
pub const BUF_SIZE_4M: usize = 4 * 1024 * 1024; // 4MB
pub const BUF_SIZE_64M: usize = 64 * 1024 * 1024; // 64MB
pub const ORDER: u64 = 250;
pub type KeyType = u64;
pub type ValueType = u64;
pub type NodeIDType = u64;
pub type AddrType = u64;
pub const LRU_CACHE_SIZE: usize = 100_000_000;
pub const MAGIC: u64 = 9236;
pub const FORMAT_STR_NAME: &str = "FORMAT";
